// JsFromRoutes CacheKey ba59be812e8e94207a191c65de69f8d3
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
export { default as pages } from '~/api/PagesApi'
export { default as authenticationLogin } from '~/api/Authentication/LoginApi'
export { default as authenticationRegister } from '~/api/Authentication/RegisterApi'
export { default as dashboardPages } from '~/api/Dashboard/PagesApi'
