// JsFromRoutes CacheKey ad21c3be3396d55dd12fc862d0aeb706
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/inertia'

export default {
  index: definePathHelper('get', '/'),
  contact: definePathHelper('get', '/contact'),
}
