// JsFromRoutes CacheKey 019f8f0a78c351b6aacd7b75135d8ef1
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/inertia'

export default {
  index: definePathHelper('get', '/login'),
}
