// JsFromRoutes CacheKey 249026238ffe2b92f19f25a57c81fd88
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/inertia'

export default {
  index: definePathHelper('get', '/register'),
}
