// JsFromRoutes CacheKey 5078d9c138ad4b8f0143b63da3285fbe
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/inertia'

export default {
  index: definePathHelper('get', '/dashboard'),
}
